# Generated by Django 4.2.11 on 2024-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/images/avatar7.png', upload_to='media/images/'),
        ),
    ]
