# Generated by Django 4.2.11 on 2024-04-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprint',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
