# Generated by Django 4.2.11 on 2024-04-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancecode',
            old_name='expiry_time',
            new_name='expiry_date',
        ),
    ]
