# Generated by Django 4.2.11 on 2024-05-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0003_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='remaining_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
