# Generated by Django 4.2.11 on 2024-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_remove_userdetails_remaining_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('fullname', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='expirt_Date',
            new_name='expiry_date',
        ),
    ]
