# Generated by Django 4.2.11 on 2024-05-09 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_studentdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='created_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
