# Generated by Django 4.2.11 on 2024-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_alter_userdetails_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
